//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPProject01.Models.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class G1_User_Account
    {
        public int id { get; set; }
        public string email { get; set; }
        public string passwd { get; set; }
    }
}
