//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPProject01.Models.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class G3_Monitor_Notice
    {
        public int Id { get; set; }
        public string User { get; set; }
        public string Object { get; set; }
        public System.DateTime MeasurementDate { get; set; }
        public int status { get; set; }
    }
}
